### ISSUE TITLE
New user can't save first container

### ISSUE THREAD

**Issue by KrisVda1** [SenneVanderAuwera/startpage#26] opened 2020-10-01 06:32 UTC
steps to recreate error:

* Create user and password
* Click on edit symbol
* Make a container with header title, linkname and linkadres
* Click ons save icon
-> Empty screen shows; container is disappeared

**Comment by SenneVanderAuwera** [comment] 2020-10-03 13:55
Apostrophes kaput

**Comment by SenneVanderAuwera** [comment] 2020-10-04 16:12
Duplicate of #21

**Closed by SenneVanderAuwera** 2020-10-04 16:12 UTC
Labels: bug
